cmake_minimum_required(VERSION 3.15)

set(OD_SOURCE_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/od)

set(OD_SOURCES
    ${OD_SOURCE_ROOT}/AudioThread.cpp
    ${OD_SOURCE_ROOT}/UIThread.cpp
    ${OD_SOURCE_ROOT}/config.c
    ${OD_SOURCE_ROOT}/audio/MonoResampler.cpp
    ${OD_SOURCE_ROOT}/audio/OnsetDetector.cpp
    ${OD_SOURCE_ROOT}/audio/Resampler.cpp
    ${OD_SOURCE_ROOT}/audio/Sample.cpp
    ${OD_SOURCE_ROOT}/audio/SampleFifo.cpp
    ${OD_SOURCE_ROOT}/audio/SampleLoadInfo.cpp
    ${OD_SOURCE_ROOT}/audio/SampleLoader.cpp
    ${OD_SOURCE_ROOT}/audio/SampleSaver.cpp
    ${OD_SOURCE_ROOT}/audio/Slice.cpp
    ${OD_SOURCE_ROOT}/audio/Slices.cpp
    ${OD_SOURCE_ROOT}/audio/SoundFileReader.cpp
    ${OD_SOURCE_ROOT}/audio/SoundFileWriter.cpp
    ${OD_SOURCE_ROOT}/audio/StereoResampler.cpp
    ${OD_SOURCE_ROOT}/audio/UniformlyPartitionedConvolution.cpp
    ${OD_SOURCE_ROOT}/audio/WavFileReader.cpp
    ${OD_SOURCE_ROOT}/audio/WavFileWriter.cpp
    ${OD_SOURCE_ROOT}/extras/BigHeap.cpp
    ${OD_SOURCE_ROOT}/extras/CardInfo.cpp
    ${OD_SOURCE_ROOT}/extras/ComplexFFT.cpp
    ${OD_SOURCE_ROOT}/extras/CosineRamp.cpp
    ${OD_SOURCE_ROOT}/extras/EWMA.cpp
    ${OD_SOURCE_ROOT}/extras/FareySequence.cpp
    ${OD_SOURCE_ROOT}/extras/FastEWMA.cpp
    ${OD_SOURCE_ROOT}/extras/FileReader.cpp
    ${OD_SOURCE_ROOT}/extras/FileWriter.cpp
    ${OD_SOURCE_ROOT}/extras/Filter.cpp
    ${OD_SOURCE_ROOT}/extras/InputStream.cpp
    ${OD_SOURCE_ROOT}/extras/LeastWasteAllocator.cpp
    ${OD_SOURCE_ROOT}/extras/LinearRamp.cpp
    ${OD_SOURCE_ROOT}/extras/Lockable.cpp
    ${OD_SOURCE_ROOT}/extras/LookupTable.cpp
    ${OD_SOURCE_ROOT}/extras/LookupTables.cpp
    ${OD_SOURCE_ROOT}/extras/Loudness.cpp
    ${OD_SOURCE_ROOT}/extras/Profiler.cpp
    ${OD_SOURCE_ROOT}/extras/Random.cpp
    ${OD_SOURCE_ROOT}/extras/RealFFT.cpp
    ${OD_SOURCE_ROOT}/extras/ReferenceCounted.cpp
    ${OD_SOURCE_ROOT}/extras/RunningMax.cpp
    ${OD_SOURCE_ROOT}/extras/RunningRMS.cpp
    ${OD_SOURCE_ROOT}/extras/SystemBuffer.cpp
    ${OD_SOURCE_ROOT}/extras/UPOLS.cpp
    ${OD_SOURCE_ROOT}/extras/Utils.cpp
    ${OD_SOURCE_ROOT}/extras/ZipArchiveReader.cpp
    ${OD_SOURCE_ROOT}/extras/ZipArchiveWriter.cpp
    ${OD_SOURCE_ROOT}/glue/AppInterpreter.cpp
    ${OD_SOURCE_ROOT}/glue/Expression.cpp
    ${OD_SOURCE_ROOT}/glue/ExpressionInterpreter.cpp
    ${OD_SOURCE_ROOT}/glue/Interpreter.cpp
    ${OD_SOURCE_ROOT}/glue/LongestPath.cpp
    ${OD_SOURCE_ROOT}/graphics/birdseye/ChainOverview.cpp
    ${OD_SOURCE_ROOT}/graphics/birdseye/XPath.cpp
    ${OD_SOURCE_ROOT}/graphics/charts/StripChart.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/BinaryIndicator.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/ComparatorView.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/DurationControl.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/Fader.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/LinkDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/MenuArc.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/ProgressBar.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/Readout.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/SixDigits.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/SoftButton.cpp
    ${OD_SOURCE_ROOT}/graphics/controls/StateMachineView.cpp
    ${OD_SOURCE_ROOT}/graphics/Cursor.cpp
    ${OD_SOURCE_ROOT}/graphics/Drawing.cpp
    ${OD_SOURCE_ROOT}/graphics/DrawingInstructions.cpp
    ${OD_SOURCE_ROOT}/graphics/fonts/consolas10.c
    ${OD_SOURCE_ROOT}/graphics/fonts/consolas12b.c
    ${OD_SOURCE_ROOT}/graphics/fonts/consolas8.c
    ${OD_SOURCE_ROOT}/graphics/fonts/courier_new16.c
    ${OD_SOURCE_ROOT}/graphics/fonts/pixelsix48.c
    ${OD_SOURCE_ROOT}/graphics/fonts/pixelsix9.c
    ${OD_SOURCE_ROOT}/graphics/FrameBuffer.cpp
    ${OD_SOURCE_ROOT}/graphics/fs/FileBrowser.cpp
    ${OD_SOURCE_ROOT}/graphics/Graphic.cpp
    ${OD_SOURCE_ROOT}/graphics/GraphicContext.cpp
    ${OD_SOURCE_ROOT}/graphics/holdview/MorphFader.cpp
    ${OD_SOURCE_ROOT}/graphics/holdview/TriggerGroup.cpp
    ${OD_SOURCE_ROOT}/graphics/lists/ListBox.cpp
    ${OD_SOURCE_ROOT}/graphics/lists/MondrianList.cpp
    ${OD_SOURCE_ROOT}/graphics/lists/SlidingList.cpp
    ${OD_SOURCE_ROOT}/graphics/MainFrameBuffer.cpp
    ${OD_SOURCE_ROOT}/graphics/meters/MiniScope.cpp
    ${OD_SOURCE_ROOT}/graphics/meters/VerticalMeter.cpp
    ${OD_SOURCE_ROOT}/graphics/recording/RecordingGraphic.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/FileSourceDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/HeadDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/HeadSubDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/PositionDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SampleEditorMainDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SampleEditorSubDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SampleView.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SliceHeadDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SliceHeadSubDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SliceList.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SlicingViewMainDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/SlicingViewSubDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/sampling/TapeHeadDisplay.cpp
    ${OD_SOURCE_ROOT}/graphics/screensavers/Blank.cpp
    ${OD_SOURCE_ROOT}/graphics/screensavers/Bubbles.cpp
    ${OD_SOURCE_ROOT}/graphics/screensavers/Lines.cpp
    ${OD_SOURCE_ROOT}/graphics/ScreenSaver.cpp
    ${OD_SOURCE_ROOT}/graphics/spotted/SpottedSection.cpp
    ${OD_SOURCE_ROOT}/graphics/spotted/SpottedStrip.cpp
    ${OD_SOURCE_ROOT}/graphics/SubFrameBuffer.cpp
    ${OD_SOURCE_ROOT}/graphics/text/Label.cpp
    ${OD_SOURCE_ROOT}/graphics/text/MultiText.cpp
    ${OD_SOURCE_ROOT}/graphics/text/RichTextBox.cpp
    ${OD_SOURCE_ROOT}/graphics/text/TextEditor.cpp
    ${OD_SOURCE_ROOT}/graphics/text/TextPanel.cpp
    ${OD_SOURCE_ROOT}/graphics/text/Utils.cpp
    ${OD_SOURCE_ROOT}/graphics/wayfinding/MoreThisWay.cpp
    ${OD_SOURCE_ROOT}/objects/Followable.cpp
    ${OD_SOURCE_ROOT}/objects/Inlet.cpp
    ${OD_SOURCE_ROOT}/objects/Object.cpp
    ${OD_SOURCE_ROOT}/objects/Option.cpp
    ${OD_SOURCE_ROOT}/objects/Outlet.cpp
    ${OD_SOURCE_ROOT}/objects/Parameter.cpp
    ${OD_SOURCE_ROOT}/objects/Port.cpp
    ${OD_SOURCE_ROOT}/objects/Repeater.cpp
    ${OD_SOURCE_ROOT}/objects/StateMachine.cpp
    ${OD_SOURCE_ROOT}/objects/TestOscillator.cpp
    ${OD_SOURCE_ROOT}/objects/adapters/ParameterAdapter.cpp
    ${OD_SOURCE_ROOT}/objects/control/ParamSetMorph.cpp
    ${OD_SOURCE_ROOT}/objects/file/FileSink.cpp
    ${OD_SOURCE_ROOT}/objects/file/FileSinkThread.cpp
    ${OD_SOURCE_ROOT}/objects/file/FileSource.cpp
    ${OD_SOURCE_ROOT}/objects/file/MonoFileSink.cpp
    ${OD_SOURCE_ROOT}/objects/file/StereoFileSink.cpp
    ${OD_SOURCE_ROOT}/objects/heads/Head.cpp
    ${OD_SOURCE_ROOT}/objects/heads/SliceHead.cpp
    ${OD_SOURCE_ROOT}/objects/heads/TapeHead.cpp
    ${OD_SOURCE_ROOT}/objects/math/Constant.cpp
    ${OD_SOURCE_ROOT}/objects/math/ConstantGain.cpp
    ${OD_SOURCE_ROOT}/objects/math/ConstantOffset.cpp
    ${OD_SOURCE_ROOT}/objects/math/Gain.cpp
    ${OD_SOURCE_ROOT}/objects/math/GainBias.cpp
    ${OD_SOURCE_ROOT}/objects/math/Multiply.cpp
    ${OD_SOURCE_ROOT}/objects/math/Sum.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/CaptureProbe.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/FifoProbe.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/LoudnessProbe.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/MinMax.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/Monitor.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/Probe.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/Stress.cpp
    ${OD_SOURCE_ROOT}/objects/measurement/TriggerProbe.cpp
    ${OD_SOURCE_ROOT}/objects/mixing/CrossFade.cpp
    ${OD_SOURCE_ROOT}/objects/mixing/Mixer.cpp
    ${OD_SOURCE_ROOT}/objects/mixing/MonoPanner.cpp
    ${OD_SOURCE_ROOT}/objects/mixing/StereoCrossFade.cpp
    ${OD_SOURCE_ROOT}/objects/mixing/StereoPanner.cpp
    ${OD_SOURCE_ROOT}/objects/mixing/StereoToMono.cpp
    ${OD_SOURCE_ROOT}/objects/timing/Comparator.cpp
    ${OD_SOURCE_ROOT}/tasks/ConnectionQueue.cpp
    ${OD_SOURCE_ROOT}/tasks/InputTask.cpp
    ${OD_SOURCE_ROOT}/tasks/ObjectList.cpp
    ${OD_SOURCE_ROOT}/tasks/OutputTask.cpp
    ${OD_SOURCE_ROOT}/tasks/Task.cpp
    ${OD_SOURCE_ROOT}/tasks/TaskScheduler.cpp
    ${OD_SOURCE_ROOT}/tasks/UnitChain.cpp
    ${OD_SOURCE_ROOT}/ui/Busy.cpp
    ${OD_SOURCE_ROOT}/ui/ChannelLEDs.cpp
    ${OD_SOURCE_ROOT}/ui/DialMap.cpp
    ${OD_SOURCE_ROOT}/ui/DialState.cpp
    ${OD_SOURCE_ROOT}/ui/EncoderHysteresis.cpp
    ${OD_SOURCE_ROOT}/ui/Job.cpp
    ${OD_SOURCE_ROOT}/ui/JobQueue.cpp
    ${OD_SOURCE_ROOT}/ui/LUTDialMap.cpp
    ${OD_SOURCE_ROOT}/ui/LinearDialMap.cpp
    ${OD_SOURCE_ROOT}/units/CustomUnit.cpp
    ${OD_SOURCE_ROOT}/units/EffectUnit.cpp
    ${OD_SOURCE_ROOT}/units/GraphCompiler.cpp
    ${OD_SOURCE_ROOT}/units/SourceUnit.cpp
    ${OD_SOURCE_ROOT}/units/Unit.cpp
)

add_library(od STATIC ${OD_SOURCES})

target_include_directories(od PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/od>
)

target_include_directories(od PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/od
    ${CMAKE_CURRENT_SOURCE_DIR}/od/glue
    ${CMAKE_CURRENT_SOURCE_DIR}/percussa
    ${CMAKE_CURRENT_SOURCE_DIR}/arch/darwin
    ${CMAKE_CURRENT_SOURCE_DIR}/arch/linux
    ${CMAKE_CURRENT_SOURCE_DIR}/hal
    ${CMAKE_CURRENT_SOURCE_DIR}/percussa/hal
    ${CMAKE_CURRENT_SOURCE_DIR}/libs/lua54
    ${CMAKE_CURRENT_SOURCE_DIR}/libs/lodepng
    ${CMAKE_CURRENT_SOURCE_DIR}/libs/miniz
)

target_compile_definitions(od PRIVATE
    BUILDOPT_TESTING
    FIRMWARE_VERSION=\"0.0.0\"
    BUILD_PROFILE=\"testing\"
)

set_target_properties(od PROPERTIES
    LINKER_LANGUAGE CXX
    POSITION_INDEPENDENT_CODE ON
)