cmake_minimum_required(VERSION 3.15)
project(ER301 CXX C)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    message(STATUS "=== Darwin native build ===")
    find_package(SDL2 QUIET)
    find_package(SDL2_ttf QUIET)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(CMAKE_CROSSCOMPILING)
        message(STATUS "=== Linux cross-compile build ===")
    else()
        message(STATUS "=== Linux native build ===")
    endif()
endif()

set(PERCUSSA_PANEL "ssp")
set(PERCUSSA_PLATFORM "host-sdl")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PERCUSSA_PLATFORM "fbdev")
endif()

if(TARGET_XMX)
    set(PERCUSSA_PANEL "xmx")
elseif(TARGET_SSP)
    set(PERCUSSA_PANEL "ssp")
endif()

include(libs/lua54/lua54.cmake)
include(libs/miniz/miniz.cmake)
include(libs/lodepng/lodepng.cmake)
include(od/od.cmake)
include(percussa/percussa.cmake)